### PR TITLE
keep the --ca-file args in all helm commands

### PR DESCRIPTION
**Pull request by orymate**
In most cases repos are referred with the URL in the helm
install/upgrade/etc, so the install/upgrade commands fail on certificate
errors too.

### CODE REVIEW

**Comment by brandond** [comment]
Hmm that's interesting. The original complaint was around chart **repos** with self-signed certs. You're correct that the current fix doesn't address pulling charts off remote servers by direct chart tarball URL. Is that something you do frequently?

**Comment by brandond** [comment]
After a bit more thinking, this is probably safe to do. Would you mind signing your commit so that the DCO check passes?

**Comment by orymate** [comment]
> You're correct that the current fix doesn't address use cases where the repo is skipped, and the chart tarball is referenced directly by URL. Is that something you do frequently?

I have a URL pointing to a chart repo in the `repo` field and refer to a chart by name in the `chart` field (also a `*` in the version field, a CA bundle in the `repoCA` a namespace in the `targetNamespace` and a yaml in the `valuesContent`). I think this is the standard usage. I get the x509 validation errors in the `helm install` or `upgrade` steps with the latest build of this container image. (Earlier versions exited at the `repo add` commands.)

I've updated the commit.

**Comment by orymate** [comment]
Is there anything else I can do?

**Review by brandond — APPROVED** [review]

**Pull request merged**
