### PR TITLE
Add dependabot to keep dockerfiles up to date

### PR DESCRIPTION
**Pull request by matttrach**
This contributes to https://github.com/k3s-io/k3s/issues/7040.

### CODE REVIEW

**Review by brandond — APPROVED** [review]

**Review by macedogm — APPROVED** [review]
LGTM

Only question is if we plan to add UpdateCLI later to bump:
1. https://github.com/k3s-io/klipper-helm/blob/5e763524fd8cab4790289e7220e04a6d2a016adc/Dockerfile.dapper#L8
2. https://github.com/k3s-io/klipper-helm/blob/5e763524fd8cab4790289e7220e04a6d2a016adc/package/Dockerfile#L4
3. https://github.com/k3s-io/klipper-helm/blob/5e763524fd8cab4790289e7220e04a6d2a016adc/package/Dockerfile#L6
4. https://github.com/k3s-io/klipper-helm/blob/5e763524fd8cab4790289e7220e04a6d2a016adc/package/Dockerfile#L15

**Review by dereknola — APPROVED** [review]

**Comment by brandond** [comment]
It would be nice to get the stuff in package/Dockerfile automated as well. I'm a little less concerned about golangci-lint since there's not any actual go code in this repo; that bit is just left over from the default project skeleton.

**Comment by brandond** [comment]
Ah, Matt got his PR merged and deleted the branch. You should move back to the archive for a release tag: https://github.com/helm/helm-mapkubeapis/archive/refs/tags/v0.4.1.tar.gz

**Comment by matttrach** [comment]
yep, that did it, thanks @brandond!

**Pull request merged**
